server:
  port: 8080

spring:
  application:
   name: myBlog

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/myblogdb
    username: root
    password: zjh6851265
    driver-class-name: com.mysql.cj.jdbc.Driver

